server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
feign:
  hystrix:
    enabled: true