server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: account
  datasource:
    name: orderingsystem
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsystem?serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper//**/*.xml
  type-aliases-package: com.sanelee.springclouddemo.entity